//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDevCompra
    {
        public int ID_DevolucionCompra { get; set; }
        public string ID_Pieza { get; set; }
        public int Cantidad { get; set; }
    
        public virtual DevolucionCompra DevolucionCompra { get; set; }
        public virtual Pieza Pieza { get; set; }
    }
}
