//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDevVenta
    {
        public int ID_DevVenta { get; set; }
        public string ID_Pieza { get; set; }
        public int CantPieza { get; set; }
    
        public virtual DevolucionVenta DevolucionVenta { get; set; }
        public virtual Pieza Pieza { get; set; }
    }
}
