//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevolucionVenta()
        {
            this.DetalleDevVenta = new HashSet<DetalleDevVenta>();
        }
    
        public int ID_DevVenta { get; set; }
        public int ID_Venta { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevVenta> DetalleDevVenta { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
