//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevolucionCompra()
        {
            this.DetalleDevCompra = new HashSet<DetalleDevCompra>();
        }
    
        public int ID_DevolucionCompras { get; set; }
        public string ID_Compra { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
    
        public virtual Compra Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevCompra> DetalleDevCompra { get; set; }
    }
}
