//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformacionDeVentas
    {
        public int ID_Venta { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public string Codigo_producto { get; set; }
        public string Tipo_pieza { get; set; }
        public string estado { get; set; }
        public decimal precio_venta { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public string ID_Cliente { get; set; }
    }
}
