//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionInventarioElectroMobile.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pieza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pieza()
        {
            this.Detalle_compra = new HashSet<Detalle_compra>();
            this.DetalleDevCompra = new HashSet<DetalleDevCompra>();
            this.DetalleReparacion = new HashSet<DetalleReparacion>();
            this.Lester_pieza = new HashSet<Lester_pieza>();
            this.Detalle_venta = new HashSet<Detalle_venta>();
            this.DetalleDevVenta = new HashSet<DetalleDevVenta>();
            this.Sustituto_piezas = new HashSet<Sustituto_piezas>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public string ID_Pieza { get; set; }
        public string ID_Proveedor { get; set; }
        public Nullable<byte> ID_Estado { get; set; }
        public byte ID_TipoPiezas { get; set; }
        public string SRCImagen { get; set; }
        public string SRCImagenCir { get; set; }
        public string SRCImagenCorr { get; set; }
        public string estante { get; set; }
        public Nullable<byte> tension { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
        public string circuito { get; set; }
        public Nullable<byte> dientes { get; set; }
        public Nullable<byte> recuento_terminales { get; set; }
        public string voltaje { get; set; }
        public string Fabricante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_compra> Detalle_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevCompra> DetalleDevCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReparacion> DetalleReparacion { get; set; }
        public virtual Estado_uso Estado_uso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lester_pieza> Lester_pieza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_venta> Detalle_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevVenta> DetalleDevVenta { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Tipo_piezas Tipo_piezas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sustituto_piezas> Sustituto_piezas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
